title: Public Library - Knowledge Base
description: A comprehensive knowledge base containing templates, references, tutorials, and project logs.
theme: just-the-docs

url: https://arenjay-ventures.github.io
baseurl: /Public-Library

aux_links:
  Portfolio Repository: https://github.com/arenjay-ventures/arenjay-ventures.github.io